eureka:
  client:
    eureka-service-url-poll-interval-seconds: 10 #默认为300秒，这里为了验证改为10秒
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    region: region-west
#    register-with-eureka: false
#      fetch-registry: falnullse
#    fetch-remote-regions-registry: