eureka:
  server:
    peer-eureka-nodes-update-interval-ms: 10000 #默认是10分钟即600000，这里为了验证改为10秒
    use-read-only-response-cache: false
    response-cache-auto-expiration-in-seconds: 10
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
